### ISSUE TITLE
New method for implementing low level instrument commands

### ISSUE THREAD

**Issue by dvincentwest** [hgrecco/pyvisa#256]
I have been contributing lately to scikit-rf, which is focused on network analyzers and less so on spectrum analyzers which use the SCPI command protocol.  We begun a refactoring of the vi module, using the updated version of pyvisa, and along the way, I came up with a neat scheme for describing the SCPI command tree as a yaml file:

example yaml file:
https://github.com/dvincentwest/scikit-rf/blob/master/skrf/vi/vna/keysight_pna_scpi.yaml

snippet
```
COMMAND_TREE:
  CALC<cnum=1>:
    DATA:
      command: {name: data, set: "<fmt=SDATA>,<data=None>", query_values: <fmt=SDATA>}
      branch:
        SNP:
          PORT: {name: snp_data, query_values: "'<ports=(1, 2)>'"}
    PAR:
      CAT:
        EXT: {name: meas_name_list, query: "", csv: True}
      DEF:
        EXT: {name: create_meas, set: "'<mname>','<param>'"}
      DEL: {name: delete_meas, set: "'<mname>'"}
      SEL: {name: selected_meas, set: "'<mname>'", query: ""}
      MNUM: {name: selected_meas_by_number, set: <mnum>, query: "", returns: int}
    FORM: {name: display_format, set: <fmt=MLOG>, query: ""}
```

The yaml file can then be parsed with a python script which outputs an object that handles the low level SCPI commands and is either subclassed by another object or attached to another object which handles the more high level functions.

example parser:
https://github.com/dvincentwest/scikit-rf/blob/master/skrf/vi/scpi/parser.py

example python SCPI driver output:
https://github.com/dvincentwest/scikit-rf/blob/master/skrf/vi/vna/keysight_pna_scpi.py

As can be seen in the code, the yaml file contains all the information about keyword arguments that must be passed, what the default values should be if any, if there is a set command, a query command, or a query_values command (a query command that uses pyvisa.query_values).  It also contains information about the return type, and if the return value is a csv list.

This kind of approach allows to describe an instrument in a very compact and 'universal' way.  Subsequently any package can write their own module to compile the object however they wish, and makes it easy to extend drivers by generating the python code programmatically.

I don't know if this has a place in pyvisa, or in lantz, but I thought I would throw it out there in case there was any interest.
